language: node_js

node_js:
    - "12.14.1"

install:
    - npm install

test:
    - npm run test

build:
    - npm run build

after_success:
    -npm run coverage

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: origin.thiss.io
    branch: master
    repo: origin.thiss.io
    on:
       all_branches: true
       condition: $TRAVIS_TAG =~ ^release-

after_script:
    - npm rebuild node-sass --force
